### PR TITLE
Encouraging use of secrets for sensitive environment variables

### PR DESCRIPTION
**Pull request by btajuddin**
Default behavior does not change, and no existing value overrides will be broken by this change.

### CODE REVIEW

**Comment by oben01** [comment]
Hello @btajuddin 
Thank u for your contribution I'll release a new version.

**Comment by oben01** [comment]
for version update you can run this commad on hack forlder : 

```bash
./update-version.sh minor ../charts/homarr/Chart.yaml
```

change the artifacthub.io/changes label on Chart.yaml to  : 
```yaml
  artifacthub.io/changes: |-
    - kind: changed
      description: use secret for sensitive data Thank to @btajuddin
```

And finally : 
```
```

**Comment by btajuddin** [comment]
@oben01 Done. Let me know if there's anything else.

**Comment by oben01** [comment]
@btajuddin Thank u for the changes. We are almost there, could u please remove 
```
    - kind: changed
      description: Update ghcr.io/ajnart/homarr docker tag to v0.15.0
    - kind: added
      description: Added single sign on env variables
```
from artifacthub.io/changes. The changes are stored in helm-index branch and updated automatically 
image

**Comment by btajuddin** [comment]
Ah, I see now. I haven't worked with artifacthub before, so I thought it was a history, not just the annotations for the current version.

**Comment by oben01** [comment]
LGTM :)

**Pull request merged**
